#!/bin/bash

if  [[ $1 = "--dark" ]]; then
    sudo chmod +x ~/.local/share/MacOSBigSurThemeConverter/MacOSBigSurDark.sh
    ~/.local/share/MacOSBigSurThemeConverter/MacOSBigSurDark.sh
elif [[ $1 = "--light" ]]; then
    sudo chmod +x ~/.local/share/MacOSBigSurThemeConverter/MacOSBigSurLight.sh
    ~/.local/share/MacOSBigSurThemeConverter/MacOSBigSurLight.sh
elif [[ $1 = "--gui" ]]; then    
    python3 ~/.local/share/MacOSBigSurThemeConverter/gui.py
elif [[ $1 = "--term" ]]; then    
    ~/.local/share/MacOSBigSurThemeConverter/MacOSBigSurThemeConverter.sh
elif [[ $1 = "--uninstall" ]]; then    
    ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh
elif [[ $1 = "--help" ]]; then
    echo -e '''
    \e[1;36mUsage: \e[0m
    \e[1;32mthemeconverter\e[0m

    \e[1;36mflags: \e[0m
    \e[1;32m--help  (Get help with the themeconverter command)
    --light (Convert to light theme)
    --dark  (Convert to dark theme)
    --term  (Launch terminal version of themeconverter)
    --gui   (Launch the gui for themeconverter)\e[0m
    '''
else
    python3 ~/.local/share/MacOSBigSurThemeConverter/gui.py
fi
